name: SeleniumTest
on: workflow_dispatch
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: mktcode/consecutive-workflow-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.COOL_SCRUM_GAMES_USERNAME }}
          password: ${{ secrets.COOL_SCRUM_GAMES_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: coolscrumgames/coolscrumgames
      
      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./CoolScrumGames/Dockerfile
          push: true
          tags: coolscrumgames/coolscrumgames:test
          labels: ${{ steps.meta.outputs.labels }}

  build:
    runs-on: ubuntu-latest
    needs: [ push_to_registry ]
    services:
      project:
        image: coolscrumgames/coolscrumgames:test
        ports:
        # <port on host>:<port on container>
        - 32825:80
    steps:
        #Setup Selenium 
      - name: Check out this repo
        uses: actions/checkout@v2   
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
           python-version: '3.9'
      - name: Install browser
        run: sudo apt-get install -y chromium-browser
      - name: Install selenium
        run: pip install webdriver-manager selenium
      - name: Run the test script
        run: python Automation.py
